// ============================================================================
// Ingestion facade — Phase C+D surface. Domain depends only on this barrel.
// Subsequent phases (engine, fetcher, discovery, extractor adapters) re-export
// here as they land; nothing is exported before it exists.
// ============================================================================

export * from "./types";
export * from "./contract";
export * from "./config";
export {
  classifyCoverage,
  countBranchRows,
  structuralDensities,
  structuralEvidence,
  type BranchCoverage,
  type CoverageInput,
  type CoverageVerdict,
  type StructureKind,
  type StructuralEvidence,
} from "./shape-signals";
export {
  analyzeBranchPage,
  isAssertableBranchAttribute,
  isAssertableBranchName,
  selectBranchRows,
  type AttributeTally,
  type BranchAttributeRejection,
  type BranchAttributeVerdict,
  type BranchPageAnalysis,
  type BranchPath,
} from "./structured";
export {
  canonicalizeHtml,
  createSha256Hex,
  deterministicHtmlCanonicalizer,
} from "./canonical";
export {
  ControlledFetcher,
  DEFAULT_POLICY,
  FetcherPolicyError,
  assertUrlAllowed,
  assertResolvedAddresses,
  hostLooksLocal,
  isPrivateV4,
  isPrivateV6,
  type ControlledFetchInput,
  type ControlledFetchOutput,
  type FetcherPolicy,
} from "./fetcher";
export { nodeResolveHost } from "./fetcher.node";
export {
BrowserDiscovery,
DISCOVERY_HINT_RULES,
locateCapabilityForUrl,
extractSameHostLinks,
normalizeDiscoveredUrl,
parseRobotsSitemap,
parseSitemapLocs,
type DiscoveryConfig,
type DiscoveryRule,
} from "./discovery";
export {
extractPeopleCandidates,
scorePeopleLink,
MAX_PEOPLE_CANDIDATES,
type PeopleCandidate,
type PeopleLinkInput,
type PeopleLinkScore,
} from "./people-discovery";
export { buildEngine, GenericIngestionEngine } from "./engine";
export {
  emailFormatValidator,
  pilotValidators,
  titlePresentValidator,
} from "./validators";
export {
  PEOPLE_CAPABILITIES,
  PEOPLE_DIRECTORY_RULE_ID,
  PEOPLE_JSON_PARSER_ID,
  PEOPLE_PARSER_ID,
  composeExtractors,
  extractPeopleJson,
  nameLike,
  peopleDirectoryValidator,
  peopleExtractor,
  peopleRoleFamily,
  peopleValidators,
  type HtmlExtractor,
  type PeopleCapability,
} from "./people";
export {
  BRANCH_DIRECTORY_RULE_ID,
  BRANCH_PARSER_ID,
  FINANCIAL_METADATA_RULE_ID,
  FINMETADATA_PARSER_ID,
  NRB_LISTING_RULE_ID,
  NRB_LISTING_PARSER_ID,
  VACANCY_RULE_ID,
  VACANCY_PARSER_ID,
  branchDirectoryExtractor,
  branchDirectoryValidator,
  financialMetadataExtractor,
  financialMetadataValidator,
  nrbListingExtractor,
  nrbListingValidator,
  nrbStructuredValidators,
  structuredValidators,
  vacancyExtractor,
  vacancyValidator,
} from "./structured";
export { LocalSqliteEvidenceWriter, LocalSourceRegistry } from "./adapters/local";
export {
  DATA_API_PARSER_ID,
  DataApiConfigError,
  dataApiDocumentSlug,
  extractDataApiPayload,
  parseDataApiConfig,
  runDataApiPass,
  type DataApiConfig,
  type DataApiExtraction,
  type DataApiPassDeps,
  type DataApiPassOptions,
  type DataApiPassOutcome,
  type DataApiPassResult,
  type DataApiRoute,
} from "./dataapi";
export {
  flagPeopleConflicts,
  listOpenConflicts,
  resolveConflict,
  reviewAssertion,
  type FlagConflictsInput,
  type OpenConflictRow,
  type ResolveConflictInput,
  type ReviewAssertionInput,
  type ReviewAssertionResult,
  type ReviewVerdict,
} from "./review";
export {
  PEOPLE_ASSERTION_ENTITY_TYPE,
  PEOPLE_ASSERTION_FIELD_PREFIX,
  applyPeopleEvidence,
  currentPeopleClaimsForSource,
  isPeopleAssertionField,
  normalizePeopleClaimValue,
  planPeopleEvidence,
  type AppliedPeopleClaim,
  type PeopleApplyContext,
  type PeopleApplyResult,
  type PeopleClaim,
  type PeopleClaimPlan,
  type PeopleConflictSide,
  type PeopleObservation,
  type PeopleObservationPlan,
  type PeopleSlotPlan,
  type PeopleWriteStatus,
} from "./people-evidence";

// M3.4 extension: external branch evidence fallback.
export {
  BRANCH_SOURCE_DB_TYPE,
  BRANCH_SOURCE_GRADE,
  BRANCH_SOURCE_PRIORITY,
  applyExternalPlan,
  branchSourcePriority,
  buildBranchSourcePlan,
  changedExternalFields,
  decideBranchEvidence,
  diffExternalRecords,
  externalBranchEntityId,
  externalRecordFingerprint,
  indexExternalRecordState,
  mapExternalHeader,
  matchInstitution,
  officialAllowsExternalFallback,
  parseExternalBranchTable,
  planExternalRepeat,
  reconcileBranchEvidence,
  registryFirstOfType,
  registryForInstitution,
  type BranchDiscoveryMethod,
  type BranchEvidenceClaim,
  type BranchEvidenceCoverage,
  type BranchEvidenceDecision,
  type BranchFieldConflict,
  type BranchReconciliation,
  type BranchReconciliationStatus,
  type BranchSourcePlan,
  type BranchSourcePlanEntry,
  type BranchSourceRegistry,
  type BranchSourceSpec,
  type BranchSourceType,
  type ExternalBranchField,
  type ExternalBranchRecord,
  type ExternalBranchTable,
  type ExternalColumnMap,
  type ExternalRecordChange,
  type ExternalRecordDelta,
  type ExternalRecordState,
  type ExternalRejectedRow,
  type ExternalRepeatPlan,
  type ExternalSourceAvailability,
  type ExternalWrite,
  type InstitutionCandidate,
  type InstitutionMatch,
  type InstitutionMatchMethod,
  type OfficialBranchSourceRef,
} from "./branch-external";

// M3.5 extension: generic career/vacancy discovery. Additive only; nothing
// above this line is re-exported, renamed or re-signed.
export {
  CAREER_DISCOVERY_THRESHOLD,
  CAREER_HREF_HINTS,
  careerLinkEvidence,
  discoverCareerTargets,
  extractCareerLinks,
  isCareerCandidate,
  isRootUrl,
  classifyDocumentLink,
  type CareerDiscoveryInput,
  type CareerDiscoveryTarget,
  type CareerEvidence,
  type CareerLink,
  type DocumentRole,
  type LinkRole,
} from "./career-discovery";

// M3.5 extension: the vacancy grammar. Additive only; nothing above this line is
// re-exported, renamed or re-signed.
export {
  CLIENT_SHELL_INDICATORS_MIN,
  CLIENT_SHELL_TEXT_MAX,
  DEPARTMENT,
  EMPLOYMENT_TYPE,
  JOB_ROLE_RE,
  JOB_TITLE,
  SOURCE_DOCUMENT,
  UNREADABLE_TEXT_MAX,
  analyzeCareerPage,
  classifyCareerShape,
  hasPlausibleDate,
  DEADLINE_MARKER_RE,
  isAssertableApplicationUrl,
  isAssertableJobTitle,
  isValidEmail,
  parseEmploymentType,
  parseIsoDate,
  parseVacancyCards,
  parseVacancyDetail,
  parseVacancyJson,
  parseVacancyList,
  parseVacancyTable,
  titleRejection,
  vacancyFingerprint,
  vacancyId,
  vacancyIdentityKey,
  vacancySlug,
  type CareerPageAnalysis,
  type CareerShape,
  type CareerShapeCounts,
  type DeadlineSupport,
  type TitleRejection,
  type VacancyField,
  type VacancyRecord,
} from "./careers";

// M3.5 extension: evidence planning and application. Additive only.
export {
  CAREER_JSON_PARSER_VERSION,
  CAREER_PARSER_VERSION,
  PUBLISHABLE_CONFIDENCE,
  VACANCY_ENTITY_TYPE,
  applyVacancyDocument,
  applyVacancyEvidence,
  isPublishableAssertion,
  planVacancyDocumentEvidence,
  planVacancyEvidence,
  type ApplyContext,
  type AppliedVacancy,
  type PlannedAssertion,
  type PlannedVacancy,
  type VacancyWriteStatus,
} from "./career-evidence";

// Phase C extension: financial document evidence. Additive only.
export {
  DOCUMENT_TITLE,
  DOCUMENT_TYPE,
  FINANCIAL_ENTITY_TYPE,
  FINANCIAL_PARSER_VERSION,
  RATE_KIND,
  applyFinancialDocument,
  classifyFinancialDocument,
  financialId,
  planFinancialDocumentEvidence,
  titleFromUrl,
  type FinancialApplyContext,
  type FinancialClassification,
  type FinancialDocumentPlan,
  type FinancialReportKind,
  type FinancialWriteStatus,
  type RateNoticeKind,
} from "./financial-evidence";