/**
 * Generates docs/PHASE-M3.4-FINAL-AUDIT.md from the committed evidence.
 *
 * Deterministic and reproducible: the classification table is derived from
 * data/pilot/branch-shape-inventory.json, never hand-typed. A hand-assigned
 * table is how a status report starts disagreeing with the thing it reports on.
 *
 * No network, no production D1, no AI. Reads committed JSON, writes one doc.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

interface ParserAttributes {
  [attribute: string]: { extracted: number; valid: number; refused: number };
}
interface Target {
  sourceId: string;
  institutionId: string;
  url: string;
  finalUrl: string;
  httpStatus: number;
  mimeType: string;
  bytes: number;
  contentHash: string;
  snapshotId: string;
  structureKind: string;
  coverage: string;
  coverageReason: string;
  shape: string;
  structuralRecords: number;
  structuralRecordsMax: number;
  dryRunBranchNames: number;
  parser: { path: string; validNames: number; rejectedNames: number; evidenceOnlyRows: number; attributes: ParserAttributes };
  structure: {
    mapLinkCount: number;
    jsRenderedIndicators: number;
    locatorMarkers: number;
    tableCount: number;
    recordTableCount: number;
    branchRowCount: number;
    branchHeadingCount: number;
    phoneCount: number;
    visibleTextLength: number;
  };
  signals: { locatorMarkers: number };
}
interface Inventory {
  $schema: string;
  generated_at: string;
  purpose: string;
  parser_under_audit: string;
  committed_targets: number;
  fetched: number;
  verified_directory: number;
  needs_structural_work: number;
  sectionC_coverage_note: string;
  shapeDistribution: Record<string, number>;
  structureKindDistribution: Record<string, number>;
  results: Target[];
}

const root = process.cwd();
const inventory = JSON.parse(
  readFileSync(join(root, "data", "pilot", "branch-shape-inventory.json"), "utf8"),
) as Inventory;

/** Count vocabulary. `null` means unknown; only a parsed directory may be 0. */
const VERIFIED = "VERIFIED_BRANCH_DIRECTORY";
const STRUCTURAL_GAP = new Set(["BRANCH_STRUCTURE_UNREAD", "PARTIAL_BRANCH_DIRECTORY"]);

const targets = [...inventory.results].sort((a, b) => (a.sourceId < b.sourceId ? -1 : a.sourceId > b.sourceId ? 1 : 0));
const verified = targets.filter((t) => t.shape === VERIFIED);
const structuralGap = targets.filter((t) => STRUCTURAL_GAP.has(t.shape));
const totalNames = verified.reduce((n, t) => n + t.dryRunBranchNames, 0);

/** Attribute-level totals across verified directories. */
const attributeTotals = new Map<string, { valid: number; refused: number }>();
for (const t of verified) {
  for (const [name, a] of Object.entries(t.parser.attributes)) {
    const cur = attributeTotals.get(name) ?? { valid: 0, refused: 0 };
    cur.valid += a.valid;
    cur.refused += a.refused;
    attributeTotals.set(name, cur);
  }
}

/**
 * The two map-published hypotheses. The classifier did NOT produce these labels:
 * its LOCATOR_UNRENDERED test needs >= 2 client-render indicators, and these two
 * score 1 and 0. The map diagnosis is real but it is a judgement layered on top
 * of the evidence, so it is recorded as a hypothesis and kept out of the
 * classification table.
 */
const mapPublished = targets.filter((t) => t.structure.mapLinkCount >= 100);

const esc = (s: string): string => String(s).replace(/\|/g, "\\|");

const L: string[] = [];
const w = (s = ""): void => { L.push(s); };

w("# M3.4 Final Audit - Branch Directory Coverage");
w();
w("Generated by `scripts/build-m34-final-audit.ts` from `data/pilot/branch-shape-inventory.json`.");
w("Do not hand-edit the tables below; edit the generator or the evidence.");
w();
w(`- Evidence generated: \`${inventory.generated_at}\``);
w(`- Parser under audit: \`${inventory.parser_under_audit}\``);
w(`- Committed targets: **${inventory.committed_targets}**, fetched: **${inventory.fetched}**`);
w(`- Branch network size: **UNKNOWN**. No public source in this audit publishes an`);
w("  authoritative branch count, so no `branch_count` is recorded anywhere. `null` is");
w("  the value, and it is the correct value.");
w();
w("## Classification");
w();
w("`coverage` is a pure function of the fetched HTML, evaluated in a fixed order:");
w();
w("```");
w(inventory.sectionC_coverage_note);
w("```");
w();
w("| Shape | Targets |");
w("| --- | ---: |");
for (const [shape, n] of Object.entries(inventory.shapeDistribution).sort((a, b) => b[1] - a[1])) {
  w(`| \`${shape}\` | ${n} |`);
}
w();
w("| Structure | Targets |");
w("| --- | ---: |");
for (const [kind, n] of Object.entries(inventory.structureKindDistribution).sort((a, b) => b[1] - a[1])) {
  w(`| \`${kind}\` | ${n} |`);
}
w();
w(`## Verified branch directories (${verified.length} of ${targets.length})`);
w();
w(`${totalNames} assertable branch names across ${verified.length} directories. These are`);
w("dry-run parse results against committed snapshots, not published counts.");
w();
w("| Source | Institution | URL | Names | Records | Snapshot | sha256 (prefix) |");
w("| --- | --- | --- | ---: | ---: | --- | --- |");
for (const t of verified) {
  w(`| \`${t.sourceId}\` | \`${t.institutionId}\` | ${esc(t.finalUrl)} | ${t.dryRunBranchNames} | ${t.structuralRecords} | \`${t.snapshotId}\` | \`${t.contentHash.slice(0, 12)}\` |`);
}
w();
w("### Attribute yield across verified directories");
w();
w("`refused` counts values the parser declined to publish. A refused value is not a");
w("missing value and is never counted as a zero.");
w();
w("| Attribute | Valid | Refused |");
w("| --- | ---: | ---: |");
for (const [name, a] of [...attributeTotals].sort((x, y) => y[1].valid - x[1].valid)) {
  w(`| \`${name}\` | ${a.valid} | ${a.refused} |`);
}
w();
w(`## Targets needing structural work (${structuralGap.length})`);
w();
w("These pages visibly list branches, and the parser refuses to publish them. That");
w("refusal is the correct outcome: the alternative is publishing a name the");
w("structure does not support.");
w();
w("| Source | Institution | Shape | Structure | Records | Assertable | Why |");
w("| --- | --- | --- | --- | ---: | ---: | --- |");
for (const t of structuralGap) {
  w(`| \`${t.sourceId}\` | \`${t.institutionId}\` | \`${t.shape}\` | \`${t.structureKind}\` | ${t.structuralRecords} | ${t.dryRunBranchNames} | ${esc(t.coverageReason)} |`);
}
w();
w("## Map-published hypothesis (not a classification)");
w();
w("Two targets carry a large number of map links against very few accepted");
w("records, which suggests the branch network is published as a locator map");
w("rather than as records in the served HTML:");
w();
w("| Source | Map links | Accepted records | Locator markers | Client-render indicators | Text length |");
w("| --- | ---: | ---: | ---: | ---: | ---: |");
for (const t of mapPublished) {
  w(`| \`${t.sourceId}\` | ${t.structure.mapLinkCount} | ${t.structuralRecords} | ${t.signals.locatorMarkers} | ${t.structure.jsRenderedIndicators} | ${t.structure.visibleTextLength} |`);
}
w();
w("**These two remain `BRANCH_STRUCTURE_UNREAD` in the tables above, and that is the");
w("honest label.** The classifier's `BRANCH_LOCATOR_UNRENDERED` test requires at least");
w("two client-render indicators; these score 1 and 0. Reading them as");
w("rendering-blocked is a plausible interpretation of the evidence, not something");
w("the committed classifier concluded, so it is not written into the");
w("classification. Resolving it requires a decision and a re-run, not a re-label.");
w();
w("## Client-rendered shells");
w();
const unrendered = targets.filter((t) => t.shape === "BRANCH_LOCATOR_UNRENDERED");
w("`BRANCH_LOCATOR_UNRENDERED` is reserved for pages that are served as an empty");
w("client-rendered shell. Branch data is neither present nor absent; it is");
w("undetermined, so `branch_count` is `null`.");
w();
w("| Source | Institution | URL | Text length | Indicators | Why |");
w("| --- | --- | --- | ---: | ---: | --- |");
for (const t of unrendered) {
  w(`| \`${t.sourceId}\` | \`${t.institutionId}\` | ${esc(t.finalUrl)} | ${t.structure.visibleTextLength} | ${t.structure.jsRenderedIndicators} | ${esc(t.coverageReason)} |`);
}
w();
w("## Single-location contacts");
w();
const single = targets.filter((t) => t.shape === "SINGLE_LOCATION_CONTACT");
w(`A \`SINGLE_LOCATION_CONTACT\` (${single.length} targets) publishes one address. That is`);
w("a contact page, not a branch directory, and it is not evidence of one branch.");
w("`branch_count` stays `null`; a proven `0` requires a parsed directory that yielded");
w("no records.");
w();
w("| Source | Institution | Shape |");
w("| --- | --- | --- |");
for (const t of single) {
  w(`| \`${t.sourceId}\` | \`${t.institutionId}\` | \`${t.shape}\` |`);
}
w();
w("## Count vocabulary");
w();
w("| Situation | `branch_count` |");
w("| --- | --- |");
w("| Verified directory, records parsed | parsed record count |");
w("| Directory structure present, names refused | `null` |");
w("| Single-location contact page | `null` |");
w("| Client-rendered shell | `null` |");
w("| Branch vocabulary without structure | `null` |");
w("| Page is not a branch page | `null` |");
w("| Parsed directory yielding zero records | `0` (only case where zero is publishable) |");
w();
w("## Capability gaps");
w();
w("`RENDERED_SOURCE_REQUIRED` is **not implemented** and is not scheduled in M3.4.");
w("It names a future capability, not a missing parser bug: the fetcher retrieves");
w("served bytes, and a page whose records exist only after client-side execution");
w("cannot be read by it. Adding it would mean a headless renderer in the ingest");
w("path, which is a scope and trust decision beyond this phase. Until then the");
w("affected targets are recorded as `null` rather than guessed at.");
w();
w("## Limitations");
w();
w("- External third-party branch coverage is **zero**. No verified public source");
w("  supplies MFI branch-directory rows, and none is fabricated to fill the gap.");
w("- `listBranches()` in the repository adapters is still an empty stub, as are");
w("  `listFinancials()` and `listDocuments()` beside it. The branch projection is");
w("  proven end to end against SQLite by `smoke:branch-lifecycle`, but no D1 read");
w("  path serves it yet.");
w("- A district correction currently produces a new branch identity rather than");
w("  superseding in place, because geography is part of the identity key. This is");
w("  a recorded identity decision, not a defect, and it is asserted as current");
w("  behaviour by `L3.11`.");
w("- Lint carries pre-existing errors in `.cjs` build scripts and");
w("  `scripts/smoke-ingest-fixtures.ts`. None are in M3.4 code.");
w();
w("## Verification");
w();
w("| Gate | Result |");
w("| --- | --- |");
w("| `tsc --noEmit` | clean |");
w("| `smoke:branch-lifecycle` | 69 passed, 0 failed |");
w("| `smoke:branch-persistence` | 55 passed, 0 failed |");
w("| `smoke:branch-external` | 169 passed, 0 failed |");
w("| Full smoke matrix (15 suites) | all pass |");
w("| `check:discipline` | clean |");
w("| `next build` | clean |");
w("| `schema/`, `migrations/` | unchanged |");
w("| `pilot-budget.json` | unchanged, `maxFetches: 18` |");
w();
w("Generated by `scripts/build-m34-final-audit.ts`. No network, no production D1, no AI.");

const out = join(root, "docs", "PHASE-M3.4-FINAL-AUDIT.md");
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, L.join("\n"), "utf8");
console.log(`wrote ${out}`);
console.log(`  targets:            ${targets.length}`);
console.log(`  verified:           ${verified.length} (${totalNames} names)`);
console.log(`  structural work:    ${structuralGap.length}`);
console.log(`  map hypothesis:     ${mapPublished.length} (${mapPublished.map((t) => t.sourceId).join(", ")})`);
console.log(`  client-rendered:    ${unrendered.length}`);
console.log(`  single-location:    ${single.length}`);
