// ============================================================================
// People evidence snapshot generator (M3.3) — reads a pilot run DB (read-only)
// and emits a deterministic `src/data/people.ts` module: the raw people
// evidence rows (data_assertions with field_name LIKE 'people_%', joined to the
// institution for slug/name provenance) plus the OPEN people conflicts, so the
// static site + B2B API can project PersonDtos (lib/repository/projection.ts)
// without touching D1.
//
//   npm run pilot:export:people -- <absolute-or-relative-db-path>
//   env LK_PILOT_DB=path npm run pilot:export:people
//
// Falls back to data/pilot/pilot-run-report.json for dbPath. READ-ONLY: no
// DDL, no writes to the source DB. Emits an empty (honest) module when the DB
// has no people evidence yet — the API then reports 0 people, never a guess.
// ============================================================================

import { createRequire } from "node:module";
import { readFileSync, existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const require = createRequire(import.meta.url);
const Database = require("better-sqlite3");

type Row = Record<string, unknown>;
type DB = {
  prepare(sql: string): { get(...args: unknown[]): Row | undefined; all(...args: unknown[]): Row[] };
  close(): void;
};

interface PersonAssertionLiteral {
  institution_id: string;
  institution_slug: string;
  institution_name: string;
  field_name: string;
  value: string;
  source_id: string;
  observed_at: string;
  verification_status: string;
  confidence: number | null;
}

interface OpenConflictLiteral {
  institution_id: string;
  field_name: string;
}

const num = (v: unknown): number | null => (v === null || v === undefined ? null : Number(v));

function main(): void {
  // People evidence lives in the People pilot DB (written by
  // scripts/run-pilot-people.ts), so that report is the preferred source of
  // truth. Falling back to the Phase O report would silently regenerate an
  // empty module and lose the verified People evidence.
  const readDbPath = (file: string, key: string): string | undefined => {
    const p = join(process.cwd(), "data", "pilot", file);
    if (!existsSync(p)) return undefined;
    const v = (JSON.parse(readFileSync(p, "utf8")) as Record<string, unknown>)[key] as string | undefined;
    return v && !v.startsWith("<") ? v : undefined;
  };
  const peoplePilot = readDbPath("pilot-people-report.json", "db_path");
  const phaseO = readDbPath("pilot-run-report.json", "dbPath");
  const dbPath = process.argv[2] ?? process.env.LK_PILOT_DB ?? peoplePilot ?? phaseO;
  console.log(`source db: ${dbPath ?? "(none)"}`);
  if (!dbPath) {
    console.error("USAGE: npm run pilot:export:people -- <db-path>   (or set LK_PILOT_DB)");
    process.exit(1);
  }
  const db = new Database(dbPath, { readonly: true }) as DB;

  const rows = db
    .prepare(
      `SELECT i.id AS institution_id, i.slug AS institution_slug, i.name_en AS institution_name,
              a.field_name, a.value, a.source_id, a.observed_at, a.verification_status, a.confidence
         FROM data_assertions a
         JOIN institutions i ON i.id = a.entity_id
        WHERE a.entity_type = 'institution' AND a.field_name LIKE 'people_%'
        ORDER BY i.slug, a.value, a.field_name, a.observed_at`,
    )
    .all();
  const people: PersonAssertionLiteral[] = rows.map((r) => ({
    institution_id: String(r.institution_id),
    institution_slug: String(r.institution_slug),
    institution_name: String(r.institution_name),
    field_name: String(r.field_name),
    value: String(r.value),
    source_id: String(r.source_id),
    observed_at: String(r.observed_at),
    verification_status: String(r.verification_status),
    confidence: num(r.confidence),
  }));

  const conflictRows = db
    .prepare(
      `SELECT entity_id, field_name FROM data_conflicts
        WHERE resolution_status = 'OPEN' AND entity_type = 'institution' AND field_name LIKE 'people_%'
        ORDER BY entity_id, field_name`,
    )
    .all();
  const openPeopleConflicts: OpenConflictLiteral[] = conflictRows.map((r) => ({
    institution_id: String(r.entity_id),
    field_name: String(r.field_name),
  }));

  const body = `// Deterministic snapshot generated by scripts/pilot-export-people.ts (read-only)
// from ingestion evidence (data_assertions + data_conflicts). Raw people
// evidence rows only — the PersonDto projection lives in
// lib/repository/projection.ts so every adapter means the same thing.
import type { PersonAssertionRecord } from "../../lib/repository/projection";

export const peopleAssertions: (PersonAssertionRecord & { confidence: number | null })[] = ${JSON.stringify(people, null, 2)};

export const openPeopleConflicts: { institution_id: string; field_name: string }[] = ${JSON.stringify(openPeopleConflicts, null, 2)};
`;

  const target = join(process.cwd(), "src", "data", "people.ts");
  writeFileSync(target, body);
  console.log(
    `WROTE ${target}\npeople assertions: ${people.length}, distinct people: ${new Set(people.map((p) => `${p.institution_id}|${p.value}`)).size}, open conflicts: ${openPeopleConflicts.length} [raw=${dbPath}]`,
  );
  db.close();
}

main();
