// Deterministic snapshot generated by scripts/pilot-export-people.ts (read-only)
// from ingestion evidence (data_assertions + data_conflicts). Raw people
// evidence rows only — the PersonDto projection lives in
// lib/repository/projection.ts so every adapter means the same thing.
import type { PersonAssertionRecord } from "../../lib/repository/projection";

export const peopleAssertions: (PersonAssertionRecord & { confidence: number | null })[] = [
  {
    "institution_id": "mfi-045",
    "institution_slug": "mfi-045",
    "institution_name": "mfi-045 (pilot stub)",
    "field_name": "people_director",
    "value": "Binodanand Jha",
    "source_id": "swastiklbs-website",
    "observed_at": "2026-09-26T18:27:21.495Z",
    "verification_status": "UNVERIFIED",
    "confidence": 0.55
  },
  {
    "institution_id": "mfi-045",
    "institution_slug": "mfi-045",
    "institution_name": "mfi-045 (pilot stub)",
    "field_name": "people_director",
    "value": "Dr. Pramod Kumar Jha",
    "source_id": "swastiklbs-website",
    "observed_at": "2026-09-26T18:27:21.495Z",
    "verification_status": "UNVERIFIED",
    "confidence": 0.55
  },
  {
    "institution_id": "mfi-045",
    "institution_slug": "mfi-045",
    "institution_name": "mfi-045 (pilot stub)",
    "field_name": "people_director",
    "value": "Jeetendra Jha",
    "source_id": "swastiklbs-website",
    "observed_at": "2026-09-26T18:27:21.495Z",
    "verification_status": "UNVERIFIED",
    "confidence": 0.55
  },
  {
    "institution_id": "mfi-045",
    "institution_slug": "mfi-045",
    "institution_name": "mfi-045 (pilot stub)",
    "field_name": "people_chair",
    "value": "Satya Narayan Jha",
    "source_id": "swastiklbs-website",
    "observed_at": "2026-09-26T18:27:21.495Z",
    "verification_status": "UNVERIFIED",
    "confidence": 0.55
  },
  {
    "institution_id": "mfi-045",
    "institution_slug": "mfi-045",
    "institution_name": "mfi-045 (pilot stub)",
    "field_name": "people_director",
    "value": "Sudhansu Shekhar Jha",
    "source_id": "swastiklbs-website",
    "observed_at": "2026-09-26T18:27:21.495Z",
    "verification_status": "UNVERIFIED",
    "confidence": 0.55
  }
];

export const openPeopleConflicts: { institution_id: string; field_name: string }[] = [];
